version: '3'

services:
  app:
    build: .
    container_name: nest-library-api
    ports:
      - "3333:3333"
      - "5555:5555" ##port for npx prisma studio
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    container_name: nest-library-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-library
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge